### ISSUE TITLE
Main View as Dashboard

### ISSUE THREAD

**Issue by rasyidf** [Kodesiana/SMBS#2]
I have implemented an idea for the main view.  it is dashboard with list of information :v @fahminlb33

**Comment by rasyidf** [comment]
![screenshoot](https://user-images.githubusercontent.com/28984914/50816858-79040d00-1354-11e9-89fc-dbe73ca3be44.jpg)

**Comment by fahminlb33** [comment]
Looks promising. But consider removing the extra features such as assignment and group tasks. It is not necessary and not the point why SMBS is developed.
